name: Swarm Upload

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ matrix.npm-version }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - run: du -hs ./out
      - run: find ./out
      - run: tar cvf website.tar out/*
      # Upload the tarball to Swarm via curl

      - name: Upload to Swarm
        uses: darkobas2/swarm-actions/upload-dir@v0.7.5
        id: upload
        with:
          dir: website.tar
          error-document: 404.html
          index-document: index.html
          bee-url: https://bee-3.fairdatasociety.org/
          timeout: 300000
          deferred: false
      - name: Setup feed
        uses: ethersphere/swarm-actions/write-feed@latest
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: "swarm-homepage"
          bee-url: https://bee-1.fairdatasociety.org
          signer: ef8ca8ca3dbccd006edbd55527194e6d29d393b4eaedd7c55831ee709c10c81d

      - uses: ethersphere/swarm-actions/reference-to-cid@v0
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
